### ISSUE TITLE
用户列表无法展示

### ISSUE THREAD

**Issue by ComeZC** [notadd/member#13]
点击用户列表，post请求返回数据正常，但是Console有报错，导致数据无法展示
     TypeError: Cannot read property 'forEach' of undefined                   app.min.js:1
debug了一下，是 resources/mixes/administration/src/pages/User.vue 的第14行，多了一个 .data 
已提交pull request

另外，点击用户标签，console会有数据打出，js代码里有console.log()调试代码未删除。。。

**Comment by zuohuadong** [comment]
已经修复
